apiVersion: v1
kind: ConfigMap
metadata:
  name: banking-config
data:
  SPRING_PROFILES_ACTIVE: "docker"
  # Service URLs
  SERVICE_AUTH_URL: "http://auth-service:8081"
  SERVICE_ACCOUNT_URL: "http://account-service:8082"
  SERVICE_TRANSACTION_URL: "http://transaction-service:8083"
  SERVICE_AUDIT_URL: "http://audit-service:8084"
  SERVICE_NOTIFICATION_URL: "http://notification-service:8085"
  ACCOUNT_SERVICE_URL: "http://account-service:8082"
  # DB Hosts
  SPRING_DATASOURCE_URL_AUTH: "jdbc:mysql://mysql-db:3306/authService"
  SPRING_DATASOURCE_URL_ACCOUNT: "jdbc:mysql://mysql-db:3306/accountService"
  SPRING_DATASOURCE_URL_TRANSACTION: "jdbc:mysql://mysql-db:3306/transactionService"
  SPRING_DATA_MONGODB_URI_AUDIT: "mongodb://${MONGODB_ADMIN_USER}:${MONGODB_ADMIN_PASS}@mongodb:27017/auditService?authSource=admin"
  SPRING_DATA_MONGODB_URI_NOTIF: "mongodb://${MONGODB_ADMIN_USER}:${MONGODB_ADMIN_PASS}@mongodb:27017/notificationService?authSource=admin"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_RABBITMQ_HOST: "rabbitmq"
