apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Pasiya12"
  AUTH_DB_USER: "authService_user"
  AUTH_DB_PASS: "authService_pass12"
  ACCOUNT_DB_USER: "accountService_user"
  ACCOUNT_DB_PASS: "accountService_pass12"
  TRANSACTION_DB_USER: "transactionService_user"
  TRANSACTION_DB_PASS: "transactionService_pass12"
  JWT_SECRET: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"
  MONGODB_ADMIN_USER: "admin"
  MONGODB_ADMIN_PASS: "Pasiya12"
