apiVersion: v1
kind: Secret
metadata:
  name: banking-secrets
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  AUTH_DB_USER: "authService_user"
  AUTH_DB_PASS: "${AUTH_DB_PASS}"
  ACCOUNT_DB_USER: "accountService_user"
  ACCOUNT_DB_PASS: "${ACCOUNT_DB_PASS}"
  TRANSACTION_DB_USER: "transactionService_user"
  TRANSACTION_DB_PASS: "${TRANSACTION_DB_PASS}"
  JWT_SECRET: "${JWT_SECRET}"
  MONGODB_ADMIN_USER: "${MONGODB_ADMIN_USER}"
  MONGODB_ADMIN_PASS: "${MONGODB_ADMIN_PASS}"
  MAIL_USERNAME: "${MAIL_USERNAME}"
  MAIL_PASSWORD: "${MAIL_PASSWORD}"
