apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: mongo:latest
          name: mongodb
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: banking-secrets
                  key: MONGODB_ADMIN_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: banking-secrets
                  key: MONGODB_ADMIN_PASS
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
            - name: init-mongo
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mongodb-data
          emptyDir: {}
        - name: init-mongo
          configMap:
            name: mongodb-init-script
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init-mongo.js: |
    db = db.getSiblingDB('admin');
    db.auth(process.env.MONGO_INITDB_ROOT_USERNAME, process.env.MONGO_INITDB_ROOT_PASSWORD);
    db = db.getSiblingDB('auditService');
    db.createUser({ user: 'admin', pwd: 'Pasiya12', roles: [{ role: 'readWrite', db: 'auditService' }] });
    db = db.getSiblingDB('notificationService');
    db.createUser({ user: 'admin', pwd: 'Pasiya12', roles: [{ role: 'readWrite', db: 'notificationService' }] });
